### ISSUE TITLE
Renderer bounds are incorrect, leading to incorrect craft size detection

### ISSUE THREAD

**Issue by NathanKell** [B9-Procedural-Wings/B9-PWings-Modified#6]
The way craft size is computed it just merges the bounds of all MeshRenderers and SkinnedMeshRenderers on all parts. Since the reported bounds are wrong in some cases (check the engineer report), I think there must be a mesh that is not having RecalculateBounds run on it, or there is a SkinnedMeshRenderer with updateWhenOffscreen not set to true.

To reproduce this issue, design an airplane with a long wing piece that has very small span that serves as the spine of a tail, and then place another pwing on that to make the actual tail. You will find that the reported craft height is wrong in some cases. I can provide examples but, well, they're all using RO (we encounter the issue there because we have quite low height limits in the SPH).

Reading through the code, I see bounds are being recalculated, but there is the issue of some meshes being turned on and off. Note that KSP just does GetComponent() so even disabled renderers will still be added to KSP's array of renderers.

**Comment by NathanKell** [comment]
Example:
![image](https://user-images.githubusercontent.com/5144098/122162463-76ad1380-ce28-11eb-80c4-541e59655c3e.png)

Note the reported height is 5.5m, despite the actual height (as measured by a procedural parts tank) being ~2.4m.
The width is also wrong; it says 8.6m but the measured width is actually 5.6m, and lastly the length is reported as 10.7m but is actually ~10.3m.

**Comment by NathanKell** [comment]
I did a test to see if it was just due to KSP not ignoring disabled renderers, and that seems to not be the case. Looks like it's some bounds that aren't getting recalculated, instead, I think.

**Comment by NathanKell** [comment]
Had a sec so I tracked this down. It is exactly as I said: the inactive meshes are not having their bounds recalculated. You can demonstrate this by adding a small wing to an object (i.e. smaller than default). Save the craft. Load the craft. Note the dimensions are wrong. Then cycle the leading and trailing edges through each possible shape. Note the dimensions become correct.

**Comment by linuxgurugamer** [comment]
Thank you.  I'm hoping someone else can take a look, otherwise I'll see if I can get some time on Monday

**Comment by NathanKell** [comment]
Awesome, thanks!

**Comment by linuxgurugamer** [comment]
@NathanKell I'm trying to reproduce this, and so far, have not been able to.  
For my test, (doing this in the SPH):
1.  I start with a MK 2 rocket fuel fuselage.  
2. I then add a PWing on the top
3. I then put a T400 tank next to it (it's horizontal, using it for a measuerment of 1.25m).  
4. I then reduce the height of the PWing to about that of the T400, so the total height of the assembly is about 2.8m
5. I save it, clear the editor, and load it again
6. The dimensions seem to be correct (both length and height).

Testing this in a fairly vanilla 1.12.1 install

**Comment by siimav** [comment]
Captured directly on stream here: https://www.twitch.tv/videos/1072146533?t=0h15m53s

**Comment by linuxgurugamer** [comment]
Yes, but he is using RO, I'm not sure if that is related.
@NathanKell If you could upload that craft file, looks like it will be a good test for me

**Comment by NathanKell** [comment]
Ok well I'm feeling dumb. @siimav pointed out that I got Stabbed By A Fork--I was on a fork that didn't have the fix to this, but this centralized fork _does_ have the fix for this. Sorry about that!

So once again, cheers to y'all for combining efforts. :)

**Comment by NathanKell** [comment]
(the commit in question: https://github.com/B9-Procedural-Wings/B9-PWings-Modified/commit/562f31fa165f7a5157dae215f54ec58ff0f71b58 )

**Comment by linuxgurugamer** [comment]
Cool, I'll release then
