### ISSUE TITLE
Craft with wheels stuck in "landed" state when in flight

### ISSUE THREAD

**Issue by Paculino** [B9-Procedural-Wings/B9-PWings-Modified#8]
I use ksp 1.10.1.2939 with RSS+RO+RP1+Principia on a freshly updated Windows 10 computer with i7-8565U
Yesterday, I installed this fork of B9 manually by removing the CKAN-installed 2:0.401 https://github.com/tetraflon/B9-PWings-Modified and putting in the contents of Gamedata from release, in order to fix the bug of B9 wings being solid black no matter what. I additionally installed Scatterer 0.0770 (the version recommended for RSS) and updated RO Tanks. The first thing I did when I noticed the "landed" state bug (which was previously caused by an update conflicting with KSPWheel in my old 1.8.1 installation), was to update RO Library, because I found out via discord that the RO Tank update might require the newest RO Library. When this did not fix the landed state bug, I tried uninstalling KOS, and then downgrading both RO Tank and RO Library to their former versions, but this also did not work. Finally, I reverted to the tetraflon B9 PWings-Modified release, and the bug went away.

Here is a screenshot of my gamedata
![image](https://user-images.githubusercontent.com/42248591/125117135-bf6c8b00-e0bb-11eb-8d57-e2d3ed5b880d.png)

It seems that having an installation with this xor kspwheel works, and without kspwheel the wings show correctly even at night when not exposed to a bright light, but when I do not have kspwheel, the game forgot that the procedural wings were resized, and in the hangar I could not resize them (in the other installation patterns I did not attempt to resize wings in the hangar because I did not have any problem with them, so this may be a problem with this fork in installations using one or more of the other mods I use).
Here is a picture of the original glitch (with KSPWheel)
![image](https://user-images.githubusercontent.com/42248591/125125740-0791aa80-e0c8-11eb-9ce8-738bf1d2f776.png)
Here is a picture of the glitch without KSPWheel
![image](https://user-images.githubusercontent.com/42248591/125125810-242de280-e0c8-11eb-8e2e-63125d97df53.png)

**Comment by NathanKell** [comment]
Please zip and upload your log on the RO discord; this doesn't necessarily seem to be a B9 pwings issue per se, so I'm not sure this is actually the right place. If I manage to figure out if there is an issue in Pwings itself then it will be, but at the moment it seems probably not?

**Comment by NathanKell** [comment]
@Paculino hasn't updated this issue yet, but per discussion this seems to be an issue related to 0.43.0.10 not working on 1.10 where previous versions did (dot8 and dot9 work fine). However, looking at the dot-10 release, there is no actual release, just a download of the repo as of the tag (and I don't see a plugins folder in that repo download). So the fact that the wings are unshaped seems due to the release being broken period, rather than merely not working on 1.10?

Either way I don't think this issue is a B9PW issue, so I think it's ok to close?

**Comment by Paculino** [comment]
I did not attempt using 0.43.0.10; I first switched to this branch a few hours before the repo was released for 0.43.0.10; instead, I experienced the stuck in landed state with 0.43.0.9, until I uninstalled KSPWheel, at which point the wings forgot their shape and I noticed I could not alter the shape in the SPH.
I agree that it is safe to close since the workaround of using 0.43.0.8 works entirely.
